#include "JavaFrontend.h"
#include <iostream>
#include <sstream>

// Check if ANTLR is available
#ifdef ANTLR_AVAILABLE
#include "JavaLexer.h"
#include "JavaParser.h"
#include "JavaParserVisitor.h"
#endif

// Simplified Java AST Visitor (placeholder for ANTLR-generated visitor)
// In a full implementation, this would be generated by ANTLR from the grammar

class JavaASTVisitor {
public:
    JavaASTVisitor(JavaFrontend* frontend) : frontend_(frontend) {}

    std::unique_ptr<ASTNode> visitCompilationUnit(antlr4::tree::ParseTree* tree) {
        auto program = std::make_unique<ProgramNode>();

        // Process package, imports, and class declarations
        for (size_t i = 0; i < tree->children.size(); ++i) {
            auto child = tree->children[i];
            if (getTextFromParseTree(child) == "class") {
                auto classDecl = frontend_->visitClassDeclaration(child);
                if (classDecl) {
                    program->addChild(std::move(classDecl));
                }
            }
        }

        return program;
    }

private:
    JavaFrontend* frontend_;
};

JavaFrontend::JavaFrontend() : language_(Language::JAVA) {
    ast_ = nullptr;
}

JavaFrontend::~JavaFrontend() = default;

bool JavaFrontend::parse(const std::string& sourceCode) {
    sourceCode_ = sourceCode;

    try {
#ifdef ANTLR_AVAILABLE
        // Use ANTLR generated parser
        return parseWithANTLR(sourceCode);
#else
        // Use fallback parser
        return parseWithFallback(sourceCode);
#endif
    } catch (const std::exception& e) {
        std::cerr << "Error parsing Java code: " << e.what() << std::endl;
        return false;
    }
}

#ifdef ANTLR_AVAILABLE
bool JavaFrontend::parseWithANTLR(const std::string& sourceCode) {
    // Initialize ANTLR components
    input_ = std::make_unique<antlr4::ANTLRInputStream>(sourceCode);
    lexer_ = std::make_unique<JavaLexer>(input_.get());
    tokens_ = std::make_unique<antlr4::CommonTokenStream>(lexer_.get());
    parser_ = std::make_unique<JavaParser>(tokens_.get());

    // Parse the input
    auto tree = parser_->compilationUnit();

    if (parser_->getNumberOfSyntaxErrors() > 0) {
        std::cerr << "Java parsing errors detected" << std::endl;
        return false;
    }

    // Build AST from parse tree
    JavaASTVisitor visitor(this);
    ast_ = std::unique_ptr<ProgramNode>(dynamic_cast<ProgramNode*>(visitor.visitCompilationUnit(tree).release()));

    return true;
}
#endif

bool JavaFrontend::parseWithFallback(const std::string& sourceCode) {
    // Fallback parser for when ANTLR is not available
    std::cout << "Using fallback Java parser (ANTLR not available)" << std::endl;

    // Simple heuristic-based parsing for basic Java structures
    ast_ = std::make_unique<ProgramNode>();

    // Look for class declarations
    size_t classPos = sourceCode.find("class ");
    if (classPos != std::string::npos) {
        size_t classNameStart = classPos + 6;
        size_t classNameEnd = sourceCode.find_first_of(" {", classNameStart);
        std::string className = sourceCode.substr(classNameStart, classNameEnd - classNameStart);

        auto classNode = std::make_unique<FunctionDeclNode>(className, "class");

        // Look for methods in the class
        std::string classBody = sourceCode.substr(classNameEnd);
        size_t methodPos = classBody.find("public ");
        if (methodPos != std::string::npos) {
            size_t methodNameStart = methodPos + 7;
            size_t methodNameEnd = classBody.find_first_of(" (", methodNameStart);
            std::string methodName = classBody.substr(methodNameStart, methodNameEnd - methodNameStart);

            auto methodNode = std::make_unique<FunctionDeclNode>(methodName, "public void");
            classNode->addChild(std::move(methodNode));
        }

        ast_->addChild(std::move(classNode));
    }

    return true;
}

std::unique_ptr<ASTNode> JavaFrontend::getAST() const {
    return std::make_unique<ProgramNode>(*ast_);
}

std::unique_ptr<ASTNode> JavaFrontend::buildASTFromParseTree(antlr4::tree::ParseTree* tree) {
    if (!tree) return nullptr;

    std::string text = getTextFromParseTree(tree);

    // Simplified AST building based on node type
    if (text == "class") {
        return visitClassDeclaration(tree);
    } else if (text.find("public") == 0 || text.find("private") == 0 || text.find("protected") == 0) {
        return visitMethodDeclaration(tree);
    } else if (text.find("int") == 0 || text.find("String") == 0 || text.find("boolean") == 0) {
        return visitFieldDeclaration(tree);
    } else if (text == "{") {
        return visitBlock(tree);
    }

    return nullptr;
}

std::unique_ptr<ASTNode> JavaFrontend::visitCompilationUnit(antlr4::tree::ParseTree* tree) {
    auto program = std::make_unique<ProgramNode>();

    for (size_t i = 0; i < tree->children.size(); ++i) {
        auto child = tree->children[i];
        auto childNode = buildASTFromParseTree(child);
        if (childNode) {
            program->addChild(std::move(childNode));
        }
    }

    return program;
}

std::unique_ptr<ASTNode> JavaFrontend::visitClassDeclaration(antlr4::tree::ParseTree* tree) {
    // Extract class name (simplified)
    std::string className = "UnknownClass";

    for (size_t i = 0; i < tree->children.size(); ++i) {
        std::string childText = getTextFromParseTree(tree->children[i]);
        if (childText != "class" && childText != "public" && childText != "{" && childText != "}") {
            className = childText;
            break;
        }
    }

    auto classNode = std::make_unique<ASTNode>(ASTNodeType::FUNCTION_DECL, className);

    // Process class body
    for (size_t i = 0; i < tree->children.size(); ++i) {
        auto child = tree->children[i];
        if (getTextFromParseTree(child) == "{") {
            // Process class body
            visitBlock(child);
        }
    }

    return classNode;
}

std::unique_ptr<ASTNode> JavaFrontend::visitMethodDeclaration(antlr4::tree::ParseTree* tree) {
    std::string methodName = "UnknownMethod";

    for (size_t i = 0; i < tree->children.size(); ++i) {
        std::string childText = getTextFromParseTree(tree->children[i]);
        if (childText != "public" && childText != "private" && childText != "protected" &&
            childText != "static" && childText != "void" && childText != "int" &&
            childText != "String" && childText != "(" && childText != ")") {
            methodName = childText;
            break;
        }
    }

    auto methodNode = std::make_unique<FunctionDeclNode>(methodName, "void");

    // Process method body
    for (size_t i = 0; i < tree->children.size(); ++i) {
        auto child = tree->children[i];
        if (getTextFromParseTree(child) == "{") {
            auto bodyNode = visitBlock(child);
            if (bodyNode) {
                methodNode->addChild(std::move(bodyNode));
            }
        }
    }

    return methodNode;
}

std::unique_ptr<ASTNode> JavaFrontend::visitFieldDeclaration(antlr4::tree::ParseTree* tree) {
    std::string fieldName = "UnknownField";
    std::string fieldType = "UnknownType";

    for (size_t i = 0; i < tree->children.size(); ++i) {
        std::string childText = getTextFromParseTree(tree->children[i]);
        if (childText == "int" || childText == "String" || childText == "boolean") {
            fieldType = childText;
        } else if (childText != ";" && childText != "=" && fieldText == "UnknownType") {
            fieldName = childText;
        }
    }

    return std::make_unique<VariableDeclNode>(fieldName, fieldType);
}

std::unique_ptr<ASTNode> JavaFrontend::visitBlock(antlr4::tree::ParseTree* tree) {
    auto blockNode = std::make_unique<ASTNode>(ASTNodeType::BLOCK);

    for (size_t i = 0; i < tree->children.size(); ++i) {
        auto child = tree->children[i];
        auto statementNode = visitStatement(child);
        if (statementNode) {
            blockNode->addChild(std::move(statementNode));
        }
    }

    return blockNode;
}

std::unique_ptr<ASTNode> JavaFrontend::visitStatement(antlr4::tree::ParseTree* tree) {
    std::string text = getTextFromParseTree(tree);

    if (text == "return") {
        return std::make_unique<ASTNode>(ASTNodeType::RETURN_STMT);
    } else if (text == "if") {
        return std::make_unique<ASTNode>(ASTNodeType::IF_STMT);
    } else if (text.find("=") != std::string::npos) {
        // Assignment statement
        return std::make_unique<ASTNode>(ASTNodeType::BINARY_OP, "=");
    }

    return nullptr;
}

std::unique_ptr<ASTNode> JavaFrontend::visitExpression(antlr4::tree::ParseTree* tree) {
    std::string text = getTextFromParseTree(tree);

    // Check if it's a literal
    if (text.length() >= 2 && ((text[0] == '"' && text.back() == '"') ||
                              (text[0] == '\'' && text.back() == '\'') ||
                              std::isdigit(text[0]))) {
        return std::make_unique<ASTNode>(ASTNodeType::LITERAL, text);
    }

    // Check if it's an identifier
    if (std::isalpha(text[0]) || text[0] == '_') {
        return std::make_unique<ASTNode>(ASTNodeType::IDENTIFIER, text);
    }

    return nullptr;
}

std::unique_ptr<ASTNode> JavaFrontend::visitLiteral(antlr4::tree::ParseTree* tree) {
    std::string text = getTextFromParseTree(tree);
    return std::make_unique<ASTNode>(ASTNodeType::LITERAL, text);
}

std::string JavaFrontend::getTextFromParseTree(antlr4::tree::ParseTree* tree) {
    if (!tree) return "";

    // In a real ANTLR implementation, this would use tree->getText()
    // For now, return a placeholder based on node type
    return "placeholder";
}

// Factory function for creating Java frontend
std::unique_ptr<FrontendBase> createJavaFrontend() {
    return std::make_unique<JavaFrontend>();
}
